# ==============================================================================
# Module manifest for module 'PS.GHOps'
# Generated by: Justin Johns
# Generated on: 2026-07-30
# ==============================================================================

@{
    # Script module or binary module file associated with this manifest.
    RootModule           = 'PS.GHOps.psm1'

    # Version number of this module.
    # Major = significant changes, breaking changes or major new features
    # Minor = new functions or features
    # Build = bug fixes and minor updates
    ModuleVersion        = '0.3.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Core')

    # ID used to uniquely identify this module
    GUID                 = 'b563c204-74a8-4ab1-9214-e413de3d7365'

    # Author of this module
    Author               = 'Justin Johns'

    # Copyright statement for this module
    Copyright            = '(c) 2026 Justin Johns. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'PowerShell operator toolkit for GitHub: human-facing reporting and administration helpers over the gh CLI. Complements the low-level PS.GitHub substrate with org-scoped reports (issues, open branches, repo file coverage, activity) and maintenance actions.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '7.4'

    # Modules that must be imported into the global environment prior to importing this module.
    # Intentionally empty: gh subcommands go through the private Invoke-GHCli and
    # REST calls through the private Invoke-GHApi, so the module depends only on
    # the gh CLI (no PowerShell-module runtime dependency). See docs/adr/0002.
    RequiredModules      = @()

    # Functions to export from this module. Populated per-PR as functions land.
    FunctionsToExport    = @(
        'Get-GHActivity'
        'Get-GHIssue'
        'Get-GHOpenBranch'
        'Get-GHRepoFile'
        'Get-GHUnpinnedAction'
        'New-GHIssue'
        'New-GHLabel'
        'Remove-GHStaleCodeScan'
    )

    # Cmdlets to export from this module
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = @()

    # Aliases to export from this module
    AliasesToExport      = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess.
    PrivateData          = @{

        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('GitHub', 'gh', 'Operations', 'Reporting', 'Automation', 'DevOps')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/johnsarie27/PS.GHOps/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/johnsarie27/PS.GHOps'

            # Release notes are auto-generated per tag from merged PR labels via
            # .github/release.yml. See:
            # https://github.com/johnsarie27/PS.GHOps/releases

        } # End of PSData hashtable

    } # End of PrivateData hashtable
}
